### ISSUE TITLE
技术问题

### ISSUE THREAD

**Issue by javahokky** [smiek2221/scripts#25]
单纯想知道点点券log参数校验导致非法请求的原因，在浏览器会这样，app却正常，一开始想到是不是做了环境的校验，试了将navigator的属性改成app环境的值，还是非法请求。

**Comment by smiek2221** [comment]
就是用了环境识别 直接用那方法是不行的 只能把代码扒下来 手动写

**Comment by javahokky** [comment]
> 就是用了环境识别 直接用那方法是不行的 只能把代码扒下来 手动写

能说下是哪个环境变量吗？

**Comment by jsnjfz** [comment]
同问，报领取任务结果：{"rtn_code":403,"rtn_msg":"非法请求！"}，想问下大佬怎么修改
